const quotes = {
  1: "The only way to do great work is to love what you do.",
  2: "Believe you can and you're halfway there.",
  3: "Your time is limited, don't waste it living someone else's life.",
  4: "It always seems impossible until it's done.",
  5: "Don't watch the clock; do what it does. Keep going.",
  6: "The future belongs to those who believe in the beauty of their dreams.",
  7: "Strive not to be a success, but rather to be of value.",
  8: "The only limit to our realization of tomorrow will be our doubts of today.",
  9: "You are never too old to set another goal or to dream a new dream.",
  10: "The way to get started is to quit talking and begin doing.",
  11: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  12: "Everything you've ever wanted is on the other side of fear.",
  13: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  14: "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  15: "The secret of getting ahead is getting started.",
  16: "You miss 100% of the shots you don't take.",
  17: "I have not failed. I've just found 10,000 ways that won't work.",
  18: "The only person you are destined to become is the person you decide to be.",
  19: "Keep your face always toward the sunshine, and shadows will fall behind you.",
  20: "The harder the conflict, the more glorious the triumph.",
  21: "Start where you are. Use what you have. Do what you can.",
  22: "Life is 10% what happens to you and 90% how you react to it.",
  23: "Whether you think you can or you think you can't, you're right.",
  24: "The mind is everything. What you think you become.",
  25: "The best time to plant a tree was 20 years ago. The second best time is now.",
  26: "An unexamined life is not worth living.",
  27: "Turn your wounds into wisdom.",
  28: "The purpose of our lives is to be happy.",
  29: "Life is what happens when you're busy making other plans.",
  30: "You only live once, but if you do it right, once is enough.",
  31: "Go confidently in the direction of your dreams. Live the life you have imagined.",
  32: "In the end, it's not the years in your life that count. It's the life in your years.",
  33: "Life is either a daring adventure or nothing at all.",
  34: "Many of life's failures are people who did not realize how close they were to success when they gave up.",
  35: "If you want to live a happy life, tie it to a goal, not to people or things.",
  36: "Never let the fear of striking out keep you from playing the game.",
  37: "Money and success don't change people; they merely amplify what is already there.",
  38: "Your time is limited, so don't waste it living someone else's life.",
  39: "The journey of a thousand miles begins with one step.",
  40: "Either you run the day, or the day runs you.",
  41: "The two most important days in your life are the day you are born and the day you find out why.",
  42: "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.",
  43: "The best revenge is massive success.",
  44: "Life shrinks or expands in proportion to one's courage.",
  45: "I am not a product of my circumstances. I am a product of my decisions.",
  46: "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.",
  47: "Rivers know this: there is no hurry. We shall get there some day.",
  48: "It is never too late to be what you might have been.",
  49: "Nothing is impossible, the word itself says 'I'm possible'!",
  50: "The only way to achieve the impossible is to believe it is possible.",
  51: "You become what you believe.",
  52: "Dream big and dare to fail.",
  53: "It does not matter how slowly you go as long as you do not stop.",
  54: "Our greatest glory is not in never falling, but in rising every time we fall.",
  55: "The secret of life is to fall seven times and to get up eight times.",
  56: "Don't count the days, make the days count.",
  57: "You are never too old to set another goal or to dream a new dream.",
  58: "Change your thoughts and you change your world.",
  59: "All our dreams can come true, if we have the courage to pursue them.",
  60: "The difference between ordinary and extraordinary is that little extra.",
  61: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
  62: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  63: "No matter what you're going through, there's a light at the end of the tunnel.",
  64: "It's not whether you get knocked down, it's whether you get up.",
  65: "If you can dream it, you can do it.",
  66: "The future depends on what you do today.",
  67: "Hardships often prepare ordinary people for an extraordinary destiny.",
  68: "The only thing standing between you and your goal is the story you keep telling yourself.",
  69: "You don't have to be great to start, but you have to start to be great.",
  70: "Dream it. Wish it. Do it.",
  71: "Success doesn't just find you. You have to go out and get it.",
  72: "The harder you work for something, the greater you'll feel when you achieve it.",
  73: "Don't stop when you're tired. Stop when you're done.",
  74: "Wake up with determination. Go to bed with satisfaction.",
  75: "Do something today that your future self will thank you for.",
  76: "Little things make big days.",
  77: "It's going to be hard, but hard does not mean impossible.",
  78: "Don't wait for opportunity. Create it.",
  79: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
  80: "The key to success is to focus on goals, not obstacles.",
  81: "Dream it. Believe it. Build it.",
  82: "If you get tired, learn to rest, not to quit.",
  83: "Don't be afraid to give up the good to go for the great.",
  84: "I find that the harder I work, the more luck I seem to have.",
  85: "Success is walking from failure to failure with no loss of enthusiasm.",
  86: "Just one small positive thought in the morning can change your whole day.",
  87: "Opportunities don't happen. You create them.",
  88: "Don't be afraid to start over. It's a new chance to rebuild what you want.",
  89: "It's not about having time, it's about making time.",
  90: "Stay positive, work hard, make it happen.",
  91: "Great things never come from comfort zones.",
  92: "Don't limit your challenges. Challenge your limits.",
  93: "Every day may not be good, but there's something good in every day.",
  94: "Push yourself, because no one else is going to do it for you.",
  95: "The only thing that's stopping you is you.",
  96: "Sometimes later becomes never. Do it now.",
  97: "Don't let yesterday take up too much of today.",
  98: "The pain you feel today will be the strength you feel tomorrow.",
  99: "Make each day your masterpiece.",
  100: "Don't wish for it, work for it.",
  101: "Small progress is still progress.",
  102: "The moment you give up is the moment you let someone else win.",
  103: "Keep going. Everything you need will come to you at the perfect time.",
  104: "Hustle until your haters ask if you're hiring.",
  105: "Your only limit is your mind.",
  106: "Be so good they can't ignore you.",
  107: "Work hard in silence, let success make the noise.",
  108: "Don't tell people your dreams. Show them.",
  109: "If you want it, work for it. It's that simple.",
  110: "Fall seven times, stand up eight.",
  111: "The comeback is always stronger than the setback.",
  112: "Dream without fear. Love without limits.",
  113: "Good things come to those who believe. Better things come to those who are patient.",
  114: "The best view comes after the hardest climb.",
  115: "Don't stop until you're proud.",
  116: "Your vibe attracts your tribe.",
  117: "She believed she could, so she did.",
  118: "You are capable of amazing things.",
  119: "Make today so awesome yesterday gets jealous.",
  120: "Don't let your fears become your limits.",
  121: "Rise up, start fresh, see the bright opportunity in each new day.",
  122: "Difficult roads often lead to beautiful destinations.",
  123: "The only approval you need is your own.",
  124: "Be the change you wish to see in the world.",
  125: "You were born to stand out, stop trying to fit in.",
  126: "Don't just exist, live.",
  127: "Create the life you can't wait to wake up to.",
  128: "If you stumble, make it part of the dance.",
  129: "You are enough.",
  130: "Stars can't shine without darkness.",
  131: "Don't quit. Suffer now and live the rest of your life as a champion.",
  132: "Be fearless in the pursuit of what sets your soul on fire.",
  133: "Don't let the fear of losing be greater than the excitement of winning.",
  134: "You must do the things you think you cannot do.",
  135: "Difficulties in life are intended to make us better, not bitter.",
  136: "Your potential is endless. Go do what you were created to do.",
  137: "The only thing that stands between you and your dream is the will to try.",
  138: "Don't downgrade your dream just to fit your reality. Upgrade your conviction.",
  139: "If it doesn't challenge you, it doesn't change you.",
  140: "Life has no remote. Get up and change it yourself.",
  141: "When you feel like quitting, think about why you started.",
  142: "The road to success and the road to failure are almost exactly the same.",
  143: "Success is not in what you have, but who you have become.",
  144: "Make each day count.",
  145: "Stop being afraid of what could go wrong and think of what could go right.",
  146: "The biggest adventure you can take is to live the life of your dreams.",
  147: "Don't let small minds convince you that your dreams are too big.",
  148: "Do what you feel in your heart to be right, for you'll be criticized anyway.",
  149: "Go the extra mile. It's never crowded.",
  150: "If you want to fly, give up everything that weighs you down.",
  151: "Your passion is waiting for your courage to catch up.",
  152: "Magic is believing in yourself. If you can do that, you can make anything happen.",
  153: "Don't worry about failures, worry about the chances you miss when you don't even try.",
  154: "You cannot have a positive life and a negative mind.",
  155: "Positive anything is better than negative nothing.",
  156: "The greatest discovery of all time is that a person can change their future.",
  157: "The only way to discover the limits of the possible is to go beyond them.",
  158: "Life is trying things to see if they work.",
  159: "You'll never find a better sparring partner than adversity.",
  160: "The flower that blooms in adversity is the rarest and most beautiful of all.",
  161: "It's not the load that breaks you down, it's the way you carry it.",
  162: "When you come out of the storm, you won't be the same person who walked in.",
  163: "The strongest hearts have the most scars.",
  164: "Be patient and tough; someday this pain will be useful to you.",
  165: "Strength grows in the moments when you think you can't go on but you keep going anyway.",
  166: "The soul that sees beauty may sometimes walk alone.",
  167: "Some people look for a beautiful place. Others make a place beautiful.",
  168: "Happiness is not something ready-made. It comes from your own actions.",
  169: "The purpose of our lives is to be happy.",
  170: "If you want to be happy, be.",
  171: "Happiness is not by chance, but by choice.",
  172: "The secret of happiness is not in doing what one likes, but in liking what one does.",
  173: "Be happy with what you have while working for what you want.",
  174: "Happiness is a direction, not a place.",
  175: "Count your age by friends, not years. Count your life by smiles, not tears.",
  176: "Let us be grateful to people who make us happy.",
  177: "For every minute you are angry you lose sixty seconds of happiness.",
  178: "Happiness often sneaks in through a door you didn't know you left open.",
  179: "The happiness of your life depends upon the quality of your thoughts.",
  180: "The greatest happiness you can have is knowing that you do not necessarily require happiness.",
  181: "Don't cry because it's over, smile because it happened.",
  182: "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
  183: "A smile is happiness you'll find right under your nose.",
  184: "Sometimes your joy is the source of your smile, but sometimes your smile can be the source of your joy.",
  185: "Wear a smile and have friends; wear a scowl and have wrinkles.",
  186: "Peace begins with a smile.",
  187: "Life is short. Smile while you still have teeth.",
  188: "A smile is a curve that sets everything straight.",
  189: "A warm smile is the universal language of kindness.",
  190: "Let us always meet each other with smile, for the smile is the beginning of love.",
  191: "If you have only one smile in you, give it to the people you love.",
  192: "Smile, it's free therapy.",
  193: "Every time you smile at someone, it is an action of love, a gift to that person.",
  194: "A smile is the light in your window that tells others that there is a caring, sharing person inside.",
  195: "Start every day with a smile and get it over with.",
  196: "Colors are the smiles of nature.",
  197: "A kind heart is a fountain of gladness, making everything in its vicinity freshen into smiles.",
  198: "Smiling is definitely one of the best beauty remedies.",
  199: "If you see someone without a smile, give them one of yours.",
  200: "Use your smile to change the world; don't let the world change your smile.",
  201: "The storm will pass. The clouds will clear. The sun will shine again.",
  202: "Even the darkest night will end and the sun will rise.",
  203: "Your current situation is not your final destination.",
  204: "Healing is not linear. Some days you'll feel okay, others not. That's normal.",
  205: "It's okay to not be okay, but it's not okay to stay that way.",
  206: "The pain you feel today is the strength you feel tomorrow.",
  207: "You have survived 100% of your worst days. You will survive this too.",
  208: "Sometimes you have to fall apart to come back stronger than ever.",
  209: "Tears are words the heart can't express.",
  210: "Don't let yesterday's sadness steal today's joy.",
  211: "Sadness flies away on the wings of time.",
  212: "Every heart has a pain. Only the way of expressing it is different.",
  213: "The deeper that sorrow carves into your being, the more joy you can contain.",
  214: "You cannot prevent the birds of sorrow from flying over your head, but you can prevent them from building nests in your hair.",
  215: "The soul would have no rainbow had the eyes no tears.",
  216: "Sometimes you have to let go to see if there was anything worth holding on to.",
  217: "The walls we build around us to keep sadness out also keeps out the joy.",
  218: "Sadness is but a wall between two gardens.",
  219: "No one can make you feel inferior without your consent.",
  220: "What's coming is better than what's gone.",
  221: "The sun will rise and we will try again.",
  222: "You're allowed to scream, you're allowed to cry, but do not give up.",
  223: "One day you'll look back and realize you worried too much about things that didn't matter.",
  224: "Maybe the journey isn't so much about becoming anything. Maybe it's about unbecoming everything that isn't really you.",
  225: "Be gentle with yourself. You're doing the best you can.",
  226: "Healing takes time. Give yourself that time.",
  227: "You are not your pain. You are not your sadness. You are not your depression.",
  228: "The wound is the place where the light enters you.",
  229: "You are stronger than you think. Braver than you believe.",
  230: "This too shall pass.",
  231: "You are not alone in your darkness. Look for the light holders.",
  232: "Sometimes the bravest thing you can do is ask for help.",
  233: "Your feelings are valid, even the painful ones.",
  234: "It's okay to take time to heal. You don't have to rush your recovery.",
  235: "Every day may not be good, but there is something good in every day.",
  236: "You have to feel it to heal it.",
  237: "The only way out is through.",
  238: "You're not broken, you're becoming.",
  239: "Sometimes you need to slow down to speed up.",
  240: "Your value doesn't decrease based on someone's inability to see your worth.",
  241: "Don't let the shadows of yesterday spoil the sunshine of tomorrow.",
  242: "Even the most beautiful flowers had to grow through dirt.",
  243: "Your mistakes don't define you. They refine you.",
  244: "Sometimes we need to lose ourselves to find ourselves.",
  245: "The comeback is always stronger than the setback.",
  246: "You are not what happened to you. You are what you choose to become.",
  247: "Every ending is a new beginning.",
  248: "The strongest people are not those who show strength in front of us but those who win battles we know nothing about.",
  249: "You can't go back and change the beginning, but you can start where you are and change the ending.",
  250: "Broken crayons still color.",
  251: "Sometimes you have to get knocked down lower than you've ever been to stand up taller than you ever were.",
  252: "Scars are just proof that you were stronger than whatever tried to hurt you.",
  253: "The people who hurt you don't have the power to break you unless you give it to them.",
  254: "Sometimes you need to be alone to realize how strong you really are.",
  255: "You're allowed to outgrow people who don't grow with you.",
  256: "Letting go doesn't mean you stop caring. It means you stop trying to force others to.",
  257: "Sometimes good things fall apart so better things can fall together.",
  258: "Don't look back. You're not going that way.",
  259: "When someone leaves, it's because someone else is about to arrive.",
  260: "Sometimes the person you'd take a bullet for ends up being the one behind the gun.",
  261: "You can't start the next chapter of your life if you keep re-reading the last one.",
  262: "People change, things go wrong, but just remember life goes on.",
  263: "It's not about waiting for the storm to pass, it's about learning to dance in the rain.",
  264: "The longer you hold on to what's hurting you, the longer you're hurting yourself.",
  265: "Sometimes you have to accept that some people are part of your history but not your destiny.",
  266: "Let go of those who bring you down and surround yourself with those who bring out the best in you.",
  267: "Sometimes you have to forget what you feel and remember what you deserve.",
  268: "Stop giving people the power to steal your joy.",
  269: "Don't let someone who did you wrong make you think there's something wrong with you.",
  270: "You can't heal in the same environment that made you sick.",
  271: "Sometimes you need to distance yourself to see things clearly.",
  272: "Don't be afraid to start over. It's a chance to build something better.",
  273: "Sometimes you have to be your own hero because sometimes the people you can't live without can live without you.",
  274: "You are not required to set yourself on fire to keep other people warm.",
  275: "Your peace is more important than driving yourself crazy trying to understand why something happened the way it did.",
  276: "Sometimes closure arrives years later, in tiny moments of understanding.",
  277: "You don't always need a plan. Sometimes you just need to breathe, trust, let go, and see what happens.",
  278: "Sometimes the wrong choices bring us to the right places.",
  279: "Life doesn't get easier. You just get stronger.",
  280: "Sometimes you have to go through the worst to get to the best.",
  281: "You have to keep moving forward even when it hurts.",
  282: "Sometimes the best thing you can do is not think, not wonder, not imagine, not obsess. Just breathe and have faith.",
  283: "Don't let your struggle become your identity.",
  284: "Sometimes the person you'd take a bullet for is the one behind the trigger.",
  285: "You can't change how people feel about you, so don't try. Just live your life and be happy.",
  286: "Sometimes you have to accept that what's meant to be will always find a way.",
  287: "You can't force someone to value or respect you. You can only accept what they give you and decide if it's enough.",
  288: "Sometimes you need to be alone, not to be lonely, but to enjoy your free time being yourself.",
  289: "You don't have to have it all figured out to move forward.",
  290: "Sometimes the hardest part isn't letting go but learning to start over.",
  291: "You can't calm the storm, so stop trying. What you can do is calm yourself. The storm will pass.",
  292: "Sometimes you have to be strong for yourself.",
  293: "You deserve to be with someone who makes you happy, not someone you have to beg to stay.",
  294: "Sometimes you have to forget what's gone, appreciate what still remains, and look forward to what's coming next.",
  295: "You can't start the next chapter if you keep rereading the last one.",
  296: "Sometimes you have to let go of the picture of what you thought life would be like and learn to find joy in the story you're actually living.",
  297: "You can't change the past, but you can ruin the present by worrying about the future.",
  298: "Sometimes you need to take a break from everyone and spend time alone to experience, appreciate, and love yourself.",
  299: "You are not responsible for other people's happiness. You are only responsible for your own.",
  300: "Sometimes you need to lose people to find yourself.",
  301: "The darkest nights produce the brightest stars.",
  302: "Your heart knows the way. Run in that direction.",
  303: "Sometimes the smallest step in the right direction ends up being the biggest step of your life.",
  304: "The universe is not outside of you. Look inside yourself; everything that you want, you already are.",
  305: "You are the artist of your own life. Don't hand the paintbrush to anyone else.",
  306: "Sometimes you have to create what you want to be a part of.",
  307: "The energy you'll spend worrying about what others think could be spent creating something amazing.",
  308: "You are not a drop in the ocean. You are the entire ocean in a drop.",
  309: "Sometimes you need to be your own lighthouse in the storm.",
  310: "The most beautiful things are not associated with money; they are memories and moments.",
  311: "You are the sky. Everything else is just weather.",
  312: "Sometimes the most powerful thing you can say is nothing at all.",
  313: "The quieter you become, the more you can hear.",
  314: "You are not required to finish the work, but neither are you free to abandon it.",
  315: "Sometimes you have to disconnect to reconnect with what's important.",
  316: "The best way to predict your future is to create it.",
  317: "You are never too old to set another goal or to dream a new dream.",
  318: "Sometimes you find yourself in the middle of nowhere, and sometimes in the middle of nowhere you find yourself.",
  319: "The only person you should try to be better than is the person you were yesterday.",
  320: "You have within you right now, everything you need to deal with whatever the world can throw at you.",
  321: "Sometimes you have to step outside of the person you've been and remember the person you were meant to be.",
  322: "The most beautiful people are those who have known defeat, known suffering, known struggle, known loss, and have found their way out.",
  323: "You were given this life because you are strong enough to live it.",
  324: "Sometimes the things we can't change end up changing us.",
  325: "The world is full of magic things, patiently waiting for our senses to grow sharper.",
  326: "You cannot find peace by avoiding life.",
  327: "Sometimes you have to lose your mind to find your peace.",
  328: "The only thing standing between you and your goal is the story you keep telling yourself.",
  329: "You have to be odd to be number one.",
  330: "Sometimes you have to be your own hero.",
  331: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  332: "You must do the things you think you cannot do.",
  333: "Sometimes you have to go through the darkness to get to the light.",
  334: "The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.",
  335: "You are the master of your destiny. You can influence, direct and control your own environment.",
  336: "Sometimes you have to let go of who you were to become who you will be.",
  337: "The only impossible journey is the one you never begin.",
  338: "You are braver than you believe, stronger than you seem, and smarter than you think.",
  339: "Sometimes you have to walk through fire to come out stronger on the other side.",
  340: "The most difficult thing is the decision to act, the rest is merely tenacity.",
  341: "You are never too small to make a difference.",
  342: "Sometimes you have to build your own dreams, or someone else will hire you to build theirs.",
  343: "The only true wisdom is in knowing you know nothing.",
  344: "You are the CEO of your own life. Hire, fire, and promote accordingly.",
  345: "Sometimes you have to embrace the chaos to find peace.",
  346: "The greatest wealth is to live content with little.",
  347: "You are the author of your own story. Make it a bestseller.",
  348: "Sometimes you have to experience the lows to appreciate the highs.",
  349: "The journey of a thousand miles begins with a single step.",
  350: "You are enough just as you are.",
  351: "Sometimes you have to fail to succeed.",
  352: "The only way to have a friend is to be one.",
  353: "You are not a tree. You can move. You can change. You can grow.",
  354: "Sometimes you have to get lost to find yourself.",
  355: "The best way to find yourself is to lose yourself in the service of others.",
  356: "You are the only one who can limit your greatness.",
  357: "Sometimes you have to go through hell to get to heaven.",
  358: "The only thing that interferes with my learning is my education.",
  359: "You are the music while the music lasts.",
  360: "Sometimes you have to have faith in things you cannot see.",
  361: "The only source of knowledge is experience.",
  362: "You are what you do, not what you say you'll do.",
  363: "Sometimes you have to hit rock bottom to realize you can only go up.",
  364: "The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails.",
  365: "You are where you need to be. Just take a deep breath.",
  366: "Sometimes you have to let people go. Everyone is not meant to stay.",
  367: "The privilege of a lifetime is to become who you truly are.",
  368: "You are worthy of the love you keep trying to give everyone else.",
  369: "Sometimes you have to make a mess to clean it up.",
  370: "The quality of your life is the quality of your relationships.",
  371: "You are your home. Stop searching for home in other people.",
  372: "Sometimes you have to say goodbye to the person you once were.",
  373: "The reward for work well done is the opportunity to do more.",
  374: "You are a masterpiece in progress.",
  375: "Sometimes you have to take the scenic route.",
  376: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.",
  377: "You are not late. You are exactly on time for your life.",
  378: "Sometimes you have to trust the journey even when you don't understand it.",
  379: "The significant problems we face cannot be solved at the same level of thinking we were at when we created them.",
  380: "You are the universe expressing itself as a human for a little while.",
  381: "Sometimes you have to walk alone to find your path.",
  382: "The time is always right to do what is right.",
  383: "You are what you believe you are.",
  384: "Sometimes you have to write your own story.",
  385: "The unexamined life is not worth living.",
  386: "You are more powerful than you know.",
  387: "Sometimes you have to experience the pain to appreciate the joy.",
  388: "The voyage of discovery is not in seeking new landscapes, but in having new eyes.",
  389: "You are never given a dream without also being given the power to make it come true.",
  390: "Sometimes you have to feel the fear and do it anyway.",
  391: "The whole secret of existence is to have no fear.",
  392: "You are the only person on earth who can use your ability.",
  393: "Sometimes you have to get uncomfortable to get comfortable.",
  394: "The world breaks everyone, and afterward, some are strong at the broken places.",
  395: "You are the result of 3.8 billion years of evolutionary success. Act like it.",
  396: "Sometimes you have to give up to go up.",
  397: "The wound is where the light enters you.",
  398: "You are the change you wish to see in the world.",
  399: "Sometimes you have to have the courage to start over.",
  400: "The years teach much which the days never know.",
  401: "You are enough. You are so enough. It is unbelievable how enough you are.",
  402: "Sometimes you have to hear 'no' to find the right 'yes'.",
  403: "The yesterday's home runs don't win today's games.",
  404: "You are capable of more than you know.",
  405: "Sometimes you have to let go of the life you planned to live the life that's waiting for you.",
  406: "There are far better things ahead than any we leave behind.",
  407: "You are loved even when you don't feel it.",
  408: "Sometimes you have to lose to win.",
  409: "There are two ways of spreading light: to be the candle or the mirror that reflects it.",
  410: "You are never too broken to be fixed.",
  411: "Sometimes you have to make mistakes to learn.",
  412: "There is no passion to be found playing small—in settling for a life that is less than the one you are capable of living.",
  413: "You are stronger than your struggles.",
  414: "Sometimes you have to say no to good things to say yes to great things.",
  415: "There is no substitute for hard work.",
  416: "You are the architect of your own destiny.",
  417: "Sometimes you have to take the first step even when you don't see the whole staircase.",
  418: "There is no such thing as failure. There are only results.",
  419: "You are what you repeatedly do.",
  420: "Sometimes you have to walk through the fire to be forged.",
  421: "There's a difference between giving up and knowing when you've had enough.",
  422: "You are where you are because of the choices you've made.",
  423: "Sometimes you have to work for what you want.",
  424: "They tried to bury us. They didn't know we were seeds.",
  425: "You become what you believe.",
  426: "Sometimes you need to be broken to be whole.",
  427: "Things don't have to change the world to be important.",
  428: "You become what you think about most of the time.",
  429: "Sometimes you need to break down to break through.",
  430: "Things turn out best for people who make the best of the way things turn out.",
  431: "You become what you give your attention to.",
  432: "Sometimes you need to close some doors to open new ones.",
  433: "Think big and don't listen to people who tell you it can't be done.",
  434: "You cannot find peace by avoiding life.",
  435: "Sometimes you need to fall to fly.",
  436: "This is your life. Do what you love, and do it often.",
  437: "You cannot swim for new horizons until you have courage to lose sight of the shore.",
  438: "Sometimes you need to go through pain to gain.",
  439: "Those who dare to fail miserably can achieve greatly.",
  440: "You cannot travel the path until you have become the path itself.",
  441: "Sometimes you need to lose yourself to find yourself.",
  442: "Time you enjoy wasting is not wasted time.",
  443: "You can't be brave if you've only had wonderful things happen to you.",
  444: "Sometimes you need to make room for better things.",
  445: "To be beautiful means to be yourself. You don't need to be accepted by others. You need to accept yourself.",
  446: "You can't cross the sea merely by standing and staring at the water.",
  447: "Sometimes you need to step back to move forward.",
  448: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
  449: "You can't help everyone, but everyone can help someone.",
  450: "Sometimes you need to stop and listen.",
  451: "To improve is to change; to be perfect is to change often.",
  452: "You can't start a fire without a spark.",
  453: "Sometimes you need to take a break.",
  454: "To live is the rarest thing in the world. Most people exist, that is all.",
  455: "You can't stop the waves, but you can learn to surf.",
  456: "Sometimes you need to trust the process.",
  457: "To see the world, things dangerous to come to, to see behind walls, to draw closer, to find each other and to feel.",
  458: "You can't use up creativity. The more you use, the more you have.",
  459: "Sometimes you need to walk through the valley to get to the mountain.",
  460: "Today is the first day of the rest of your life.",
  461: "You can't wait for inspiration. You have to go after it with a club.",
  462: "Sometimes your only available transportation is a leap of faith.",
  463: "Today you are you, that is truer than true. There is no one alive who is youer than you.",
  464: "You deserve to be happy. You deserve to live a life you are excited about.",
  465: "Sometimes you're ahead, sometimes you're behind. The race is long, and in the end, it's only with yourself.",
  466: "Too many of us are not living our dreams because we are living our fears.",
  467: "You didn't come this far to only come this far.",
  468: "Sometimes your heart needs more time to accept what your mind already knows.",
  469: "Try not to become a person of success, but rather try to become a person of value.",
  470: "You don't have to be perfect to be amazing.",
  471: "Sometimes you've got to create what you want to be a part of.",
  472: "Turn your wounds into wisdom.",
  473: "You don't have to see the whole staircase, just take the first step.",
  474: "Tough times never last, but tough people do.",
  475: "You don't need anyone's permission to be yourself.",
  476: "Two roads diverged in a wood, and I—I took the one less traveled by, and that has made all the difference.",
  477: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
  478: "Usually the person who is trying to keep everyone happy is the most lonely.",
  479: "You have to accept whatever comes and the only important thing is that you meet it with courage.",
  480: "Wake up with determination. Go to bed with satisfaction.",
  481: "You have to be at your strongest when you're feeling at your weakest.",
  482: "Walk as if you are kissing the Earth with your feet.",
  483: "You have to fight through some bad days to earn the best days of your life.",
  484: "Wander often, wonder always.",
  485: "You have to let go of who you were to become who you will be.",
  486: "Wanting to be someone else is a waste of the person you are.",
  487: "You have to love yourself before anyone else can.",
  488: "Water does not resist. Water flows.",
  489: "You have to make the choices that are right for you.",
  490: "We are all in the gutter, but some of us are looking at the stars.",
  491: "You have to risk going too far to discover just how far you can go.",
  492: "We are made of star stuff.",
  493: "You have within you right now, everything you need to deal with whatever the world can throw at you.",
  494: "We become what we think about.",
  495: "You haven't failed until you've stopped trying.",
  496: "We can complain because rose bushes have thorns, or rejoice because thorn bushes have roses.",
  497: "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
  498: "We cannot solve our problems with the same thinking we used when we created them.",
  499: "You learn more from failure than from success.",
  500: "We don't see things as they are, we see them as we are.",
  501: "You may be the only person left who believes in you, but it's enough.",
  502: "We keep moving forward, opening new doors, and doing new things, because we're curious and curiosity keeps leading us down new paths.",
  503: "You must be the change you wish to see in the world.",
  504: "We must be willing to let go of the life we planned so as to have the life that is waiting for us.",
  505: "You must do the things you think you cannot do.",
  506: "We need never be hopeless because we can never be irreparably broken.",
  507: "You never know how strong you are until being strong is your only choice.",
  508: "We should not judge people by their peak of excellence, but by the distance they have traveled from the point where they started.",
  509: "You never know what's around the corner. It could be everything. Or it could be nothing. You keep putting one foot in front of the other, and then one day you look back and you've climbed a mountain.",
  510: "We suffer more often in imagination than in reality.",
  511: "You only fail when you stop trying.",
  512: "We swallow greedily any lie that flatters us, but we sip little by little at a truth we find bitter.",
  513: "You only live once, but if you do it right, once is enough.",
  514: "We're all stories in the end. Just make it a good one.",
  515: "You were born to be real, not to be perfect.",
  516: "What comes easy won't last. What lasts won't come easy.",
  517: "You were given this life because you are strong enough to live it.",
  518: "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  519: "You were not created to just survive. You were created to thrive.",
  520: "What we achieve inwardly will change outer reality.",
  521: "You will face many defeats in life, but never let yourself be defeated.",
  522: "What we think, we become.",
  523: "You will find that it is necessary to let things go; simply for the reason that they are heavy.",
  524: "What you do makes a difference, and you have to decide what kind of difference you want to make.",
  525: "You will never know your limits until you push yourself to them.",
  526: "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  527: "You will never be able to escape from your heart. So it is better to listen to what it has to say.",
  528: "What you seek is seeking you.",
  529: "You would not have called if you had not heard me call.",
  530: "Whatever you are, be a good one.",
  531: "You'll learn, as you get older, that rules are made to be broken.",
  532: "Whatever you can do, or dream you can, begin it.",
  533: "You'll never find a rainbow if you're looking down.",
  534: "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.",
  535: "Your attitude determines your direction.",
  536: "When I let go of what I am, I become what I might be.",
  537: "Your biggest challenge isn't someone else. It's the ache in your lungs and the burning in your legs.",
  538: "When one door closes, another opens; but we often look so long and so regretfully upon the closed door that we do not see the one which has opened for us.",
  539: "Your future is created by what you do today, not tomorrow.",
  540: "When we are no longer able to change a situation, we are challenged to change ourselves.",
  541: "Your life does not get better by chance, it gets better by change.",
  542: "When you come to the end of your rope, tie a knot and hang on.",
  543: "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
  544: "When you focus on the good, the good gets better.",
  545: "Your only limit is your mind.",
  546: "When you have a dream, you've got to grab it and never let go.",
  547: "Your present circumstances don't determine where you can go; they merely determine where you start.",
  548: "When you reach the end of what you should know, you will be at the beginning of what you should sense.",
  549: "Your struggles develop your strengths.",
  550: "When you stop expecting people to be perfect, you can like them for who they are.",
  551: "Your time is limited, so don't waste it living someone else's life.",
  552: "When you want something, all the universe conspires in helping you to achieve it.",
  553: "Your vibe attracts your tribe.",
  554: "Where there is love there is life.",
  555: "You're allowed to be both a masterpiece and a work in progress simultaneously.",
  556: "Where there is no struggle, there is no strength.",
  557: "You're braver than you believe, stronger than you seem, and smarter than you think.",
  558: "Wherever you go, go with all your heart.",
  559: "You're never too old to set another goal or to dream a new dream.",
  560: "Whether you think you can or you think you can't, you're right.",
  561: "You've always had the power, my dear. You just had to learn it for yourself.",
  562: "While we are postponing, life speeds by.",
  563: "Yesterday is history, tomorrow is a mystery, today is a gift. That is why it is called the present.",
  564: "Who looks outside, dreams; who looks inside, awakes.",
  565: "You are exactly where you need to be.",
  566: "Why fit in when you were born to stand out?",
  567: "You are never too old to become younger.",
  568: "Winning doesn't always mean being first. Winning means you're doing better than you've done before.",
  569: "You are stronger than you think.",
  570: "Without deviation from the norm, progress is not possible.",
  571: "You become what you believe.",
  572: "Without hard work, nothing grows but weeds.",
  573: "You can have it all. Just not all at once.",
  574: "Without leaps of imagination or dreaming, we lose the excitement of possibilities.",
  575: "You can never cross the ocean until you have the courage to lose sight of the shore.",
  576: "Without music, life would be a mistake.",
  577: "You can't be great if you don't feel great.",
  578: "Work hard in silence, let success make the noise.",
  579: "You can't connect the dots looking forward; you can only connect them looking backward.",
  580: "Worry does not empty tomorrow of its sorrow. It empties today of its strength.",
  581: "You can't fall if you don't climb. But there's no joy in living your whole life on the ground.",
  582: "Write it on your heart that every day is the best day in the year.",
  583: "You can't go back and change the beginning, but you can start where you are and change the ending.",
  584: "Yes, you can be a dreamer and a doer too, if you will remove one word from your vocabulary: impossible.",
  585: "You can't stop the waves, but you can learn to surf.",
  586: "You are allowed to be both a masterpiece and a work in progress simultaneously.",
  587: "You can't use up creativity. The more you use, the more you have.",
  588: "You are braver than you believe, stronger than you seem, and smarter than you think.",
  589: "You can't wait for inspiration. You have to go after it with a club.",
  590: "You are enough just as you are.",
  591: "You deserve to be happy. You deserve to live a life you are excited about.",
  592: "You are exactly where you need to be.",
  593: "You didn't come this far to only come this far.",
  594: "You are loved even when you don't feel it.",
  595: "You don't have to be great to start, but you have to start to be great.",
  596: "You are more powerful than you know.",
  597: "You don't have to see the whole staircase, just take the first step.",
  598: "You are never given a dream without also being given the power to make it come true.",
  599: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
  600: "You are never too broken to be fixed.",
  601: "You have to accept whatever comes and the only important thing is that you meet it with courage.",
  602: "You are never too old to set another goal or to dream a new dream.",
  603: "You have to be at your strongest when you're feeling at your weakest.",
  604: "You are not a tree. You can move. You can change. You can grow.",
  605: "You have to fight through some bad days to earn the best days of your life.",
  606: "You are not late. You are exactly on time for your life.",
  607: "You have to let go of who you were to become who you will be.",
  608: "You are not required to set yourself on fire to keep other people warm.",
  609: "You have to love yourself before anyone else can.",
  610: "You are not what happened to you. You are what you choose to become.",
  611: "You have to make the choices that are right for you.",
  612: "You are stronger than your struggles.",
  613: "You have to risk going too far to discover just how far you can go.",
  614: "You are the architect of your own destiny.",
  615: "You have within you right now, everything you need to deal with whatever the world can throw at you.",
  616: "You are the artist of your own life. Don't hand the paintbrush to anyone else.",
  617: "You haven't failed until you've stopped trying.",
  618: "You are the author of your own story. Make it a bestseller.",
  619: "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
  620: "You are the CEO of your own life. Hire, fire, and promote accordingly.",
  621: "You learn more from failure than from success.",
  622: "You are the change you wish to see in the world.",
  623: "You may be the only person left who believes in you, but it's enough.",
  624: "You are the master of your destiny. You can influence, direct and control your own environment.",
  625: "You must be the change you wish to see in the world.",
  626: "You are the music while the music lasts.",
  627: "You must do the things you think you cannot do.",
  628: "You are the only one who can limit your greatness.",
  629: "You never know how strong you are until being strong is your only choice.",
  630: "You are the only person on earth who can use your ability.",
  631: "You never know what's around the corner. It could be everything. Or it could be nothing. You keep putting one foot in front of the other, and then one day you look back and you've climbed a mountain.",
  632: "You are the result of 3.8 billion years of evolutionary success. Act like it.",
  633: "You only fail when you stop trying.",
  634: "You are the sky. Everything else is just weather.",
  635: "You only live once, but if you do it right, once is enough.",
  636: "You are the universe expressing itself as a human for a little while.",
  637: "You were born to be real, not to be perfect.",
  638: "You are what you believe you are.",
  639: "You were born to stand out, stop trying to fit in.",
  640: "You are what you do, not what you say you'll do.",
  641: "You were given this life because you are strong enough to live it.",
  642: "You are what you repeatedly do.",
  643: "You were not created to just survive. You were created to thrive.",
  644: "You are what you think about all day long.",
  645: "You will face many defeats in life, but never let yourself be defeated.",
  646: "You are where you are because of the choices you've made.",
  647: "You will find that it is necessary to let things go; simply for the reason that they are heavy.",
  648: "You are where you need to be. Just take a deep breath.",
  649: "You will never know your limits until you push yourself to them.",
  650: "You are worthy of the love you keep trying to give everyone else.",
  651: "You will never be able to escape from your heart. So it is better to listen to what it has to say.",
  652: "You become what you give your attention to.",
  653: "You would not have called if you had not heard me call.",
  654: "You cannot find peace by avoiding life.",
  655: "You'll learn, as you get older, that rules are made to be broken.",
  656: "You cannot swim for new horizons until you have courage to lose sight of the shore.",
  657: "You'll never find a rainbow if you're looking down.",
  658: "You cannot travel the path until you have become the path itself.",
  659: "Your attitude determines your direction.",
  660: "You can't be brave if you've only had wonderful things happen to you.",
  661: "Your biggest challenge isn't someone else. It's the ache in your lungs and the burning in your legs.",
  662: "You can't cross the sea merely by standing and staring at the water.",
  663: "Your future is created by what you do today, not tomorrow.",
  664: "You can't help everyone, but everyone can help someone.",
  665: "Your life does not get better by chance, it gets better by change.",
  666: "You can't start a fire without a spark.",
  667: "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
  668: "You can't stop the waves, but you can learn to surf.",
  669: "Your only limit is your mind.",
  670: "You can't use up creativity. The more you use, the more you have.",
  671: "Your present circumstances don't determine where you can go; they merely determine where you start.",
  672: "You can't wait for inspiration. You have to go after it with a club.",
  673: "Your struggles develop your strengths.",
  674: "You deserve to be happy. You deserve to live a life you are excited about.",
  675: "Your time is limited, so don't waste it living someone else's life.",
  676: "You didn't come this far to only come this far.",
  677: "Your vibe attracts your tribe.",
  678: "You don't have to be perfect to be amazing.",
  679: "You're allowed to be both a masterpiece and a work in progress simultaneously.",
  680: "You don't have to see the whole staircase, just take the first step.",
  681: "You're braver than you believe, stronger than you seem, and smarter than you think.",
  682: "You don't need anyone's permission to be yourself.",
  683: "You're never too old to set another goal or to dream a new dream.",
  684: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
  685: "You've always had the power, my dear. You just had to learn it for yourself.",
  686: "You have to accept whatever comes and the only important thing is that you meet it with courage.",
  687: "You are exactly where you need to be.",
  688: "You have to be at your strongest when you're feeling at your weakest.",
  689: "You are never too old to become younger.",
  690: "You have to fight through some bad days to earn the best days of your life.",
  691: "You are stronger than you think.",
  692: "You have to let go of who you were to become who you will be.",
  693: "You become what you believe.",
  694: "You have to love yourself before anyone else can.",
  695: "You can have it all. Just not all at once.",
  696: "You have to make the choices that are right for you.",
  697: "You can never cross the ocean until you have the courage to lose sight of the shore.",
  698: "You have to risk going too far to discover just how far you can go.",
  699: "You can't be great if you don't feel great.",
  700: "You have within you right now, everything you need to deal with whatever the world can throw at you.",
  701: "You can't connect the dots looking forward; you can only connect them looking backward.",
  702: "You haven't failed until you've stopped trying.",
  703: "You can't fall if you don't climb. But there's no joy in living your whole life on the ground.",
  704: "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
  705: "You can't go back and change the beginning, but you can start where you are and change the ending.",
  706: "You learn more from failure than from success.",
  707: "You can't stop the waves, but you can learn to surf.",
  708: "You may be the only person left who believes in you, but it's enough.",
  709: "You can't use up creativity. The more you use, the more you have.",
  710: "You must be the change you wish to see in the world.",
  711: "You can't wait for inspiration. You have to go after it with a club.",
  712: "You must do the things you think you cannot do.",
  713: "You deserve to be happy. You deserve to live a life you are excited about.",
  714: "You never know how strong you are until being strong is your only choice.",
  715: "You didn't come this far to only come this far.",
  716: "You never know what's around the corner. It could be everything. Or it could be nothing.",
  717: "You don't have to be perfect to be amazing.",
  718: "You only fail when you stop trying.",
  719: "You don't have to see the whole staircase, just take the first step.",
  720: "You only live once, but if you do it right, once is enough.",
  721: "You don't need anyone's permission to be yourself.",
  722: "You were born to be real, not to be perfect.",
  723: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
  724: "You were born to stand out, stop trying to fit in.",
  725: "You have to accept whatever comes and the only important thing is that you meet it with courage.",
  726: "You were given this life because you are strong enough to live it.",
  727: "You have to be at your strongest when you're feeling at your weakest.",
  728: "You were not created to just survive. You were created to thrive.",
  729: "You have to fight through some bad days to earn the best days of your life.",
  730: "You will face many defeats in life, but never let yourself be defeated.",
  731: "You have to let go of who you were to become who you will be.",
  732: "You will find that it is necessary to let things go; simply for the reason that they are heavy.",
  733: "You have to love yourself before anyone else can.",
  734: "You will never know your limits until you push yourself to them.",
  735: "You have to make the choices that are right for you.",
  736: "You will never be able to escape from your heart. So it is better to listen to what it has to say.",
  737: "You have to risk going too far to discover just how far you can go.",
  738: "You would not have called if you had not heard me call.",
  739: "You have within you right now, everything you need to deal with whatever the world can throw at you.",
  740: "You'll learn, as you get older, that rules are made to be broken.",
  741: "You haven't failed until you've stopped trying.",
  742: "You'll never find a rainbow if you're looking down.",
  743: "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
  744: "Your attitude determines your direction.",
  745: "You learn more from failure than from success.",
  746: "Your biggest challenge isn't someone else. It's the ache in your lungs and the burning in your legs.",
  747: "You may be the only person left who believes in you, but it's enough.",
  748: "Your future is created by what you do today, not tomorrow.",
  749: "You must be the change you wish to see in the world.",
  750: "Your life does not get better by chance, it gets better by change.",
  751: "You must do the things you think you cannot do.",
  752: "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
  753: "You never know how strong you are until being strong is your only choice.",
  754: "Your only limit is your mind.",
  755: "You never know what's around the corner. It could be everything. Or it could be nothing.",
  756: "Your present circumstances don't determine where you can go; they merely determine where you start.",
  757: "You only fail when you stop trying.",
  758: "Your struggles develop your strengths.",
  759: "You only live once, but if you do it right, once is enough.",
  760: "Your time is limited, so don't waste it living someone else's life.",
  761: "You were born to be real, not to be perfect.",
  762: "Your vibe attracts your tribe.",
  763: "You were born to stand out, stop trying to fit in.",
  764: "You're allowed to be both a masterpiece and a work in progress simultaneously.",
  765: "You were given this life because you are strong enough to live it.",
  766: "You're braver than you believe, stronger than you seem, and smarter than you think.",
  767: "You were not created to just survive. You were created to thrive.",
  768: "You're never too old to set another goal or to dream a new dream.",
  769: "You will face many defeats in life, but never let yourself be defeated.",
  770: "You've always had the power, my dear. You just had to learn it for yourself.",
  771: "You will find that it is necessary to let things go; simply for the reason that they are heavy.",
  772: "You are exactly where you need to be.",
  773: "You will never know your limits until you push yourself to them.",
  774: "You are never too old to become younger.",
  775: "You will never be able to escape from your heart. So it is better to listen to what it has to say.",
  776: "You are stronger than you think.",
  777: "You would not have called if you had not heard me call.",
  778: "You become what you believe.",
  779: "You'll learn, as you get older, that rules are made to be broken.",
  780: "You can have it all. Just not all at once.",
  781: "You'll never find a rainbow if you're looking down.",
  782: "You can never cross the ocean until you have the courage to lose sight of the shore.",
  783: "Your attitude determines your direction.",
  784: "You can't be great if you don't feel great.",
  785: "Your biggest challenge isn't someone else. It's the ache in your lungs and the burning in your legs.",
  786: "You can't connect the dots looking forward; you can only connect them looking backward.",
  787: "Your future is created by what you do today, not tomorrow.",
  788: "You can't fall if you don't climb. But there's no joy in living your whole life on the ground.",
  789: "Your life does not get better by chance, it gets better by change.",
  790: "You can't go back and change the beginning, but you can start where you are and change the ending.",
  791: "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
  792: "You can't stop the waves, but you can learn to surf.",
  793: "Your only limit is your mind.",
  794: "You can't use up creativity. The more you use, the more you have.",
  795: "Your present circumstances don't determine where you can go; they merely determine where you start.",
  796: "You can't wait for inspiration. You have to go after it with a club.",
  797: "Your struggles develop your strengths.",
  798: "You deserve to be happy. You deserve to live a life you are excited about.",
  799: "Your time is limited, so don't waste it living someone else's life.",
  800: "You didn't come this far to only come this far.",
  801: "Your vibe attracts your tribe.",
  802: "You don't have to be perfect to be amazing.",
  803: "You're allowed to be both a masterpiece and a work in progress simultaneously.",
  804: "You don't have to see the whole staircase, just take the first step.",
  805: "You're braver than you believe, stronger than you seem, and smarter than you think.",
  806: "You don't need anyone's permission to be yourself.",
  807: "You're never too old to set another goal or to dream a new dream.",
  808: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
  809: "You've always had the power, my dear. You just had to learn it for yourself.",
  810: "You have to accept whatever comes and the only important thing is that you meet it with courage.",
  811: "You are exactly where you need to be.",
  812: "You have to be at your strongest when you're feeling at your weakest.",
  813: "You are never too old to become younger.",
  814: "You have to fight through some bad days to earn the best days of your life.",
  815: "You are stronger than you think.",
  816: "You have to let go of who you were to become who you will be.",
  817: "You become what you believe.",
  818: "You have to love yourself before anyone else can.",
  819: "You can have it all. Just not all at once.",
  820: "You have to make the choices that are right for you.",
  821: "You can never cross the ocean until you have the courage to lose sight of the shore.",
  822: "You have to risk going too far to discover just how far you can go.",
  823: "You can't be great if you don't feel great.",
  824: "You have within you right now, everything you need to deal with whatever the world can throw at you.",
  825: "You can't connect the dots looking forward; you can only connect them looking backward.",
  826: "You haven't failed until you've stopped trying.",
  827: "You can't fall if you don't climb. But there's no joy in living your whole life on the ground.",
  828: "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
  829: "You can't go back and change the beginning, but you can start where you are and change the ending.",
  830: "You learn more from failure than from success.",
  831: "You can't stop the waves, but you can learn to surf.",
  832: "You may be the only person left who believes in you, but it's enough.",
  833: "You can't use up creativity. The more you use, the more you have.",
  834: "You must be the change you wish to see in the world.",
  835: "You can't wait for inspiration. You have to go after it with a club.",
  836: "You must do the things you think you cannot do.",
  837: "You deserve to be happy. You deserve to live a life you are excited about.",
  838: "You never know how strong you are until being strong is your only choice.",
  839: "You didn't come this far to only come this far.",
  840: "You never know what's around the corner. It could be everything. Or it could be nothing.",
  841: "You don't have to be perfect to be amazing.",
  842: "You only fail when you stop trying.",
  843: "You don't have to see the whole staircase, just take the first step.",
  844: "You only live once, but if you do it right, once is enough.",
  845: "You don't need anyone's permission to be yourself.",
  846: "You were born to be real, not to be perfect.",
  847: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
  848: "You were born to stand out, stop trying to fit in.",
  849: "You have to accept whatever comes and the only important thing is that you meet it with courage.",
  850: "You were given this life because you are strong enough to live it.",
  851: "You have to be at your strongest when you're feeling at your weakest.",
  852: "You were not created to just survive. You were created to thrive.",
  853: "You have to fight through some bad days to earn the best days of your life.",
  854: "You will face many defeats in life, but never let yourself be defeated.",
  855: "You have to let go of who you were to become who you will be.",
  856: "You will find that it is necessary to let things go; simply for the reason that they are heavy.",
  857: "You have to love yourself before anyone else can.",
  858: "You will never know your limits until you push yourself to them.",
  859: "You have to make the choices that are right for you.",
  860: "You will never be able to escape from your heart. So it is better to listen to what it has to say.",
  861: "You have to risk going too far to discover just how far you can go.",
  862: "You would not have called if you had not heard me call.",
  863: "You have within you right now, everything you need to deal with whatever the world can throw at you.",
  864: "You'll learn, as you get older, that rules are made to be broken.",
  865: "You haven't failed until you've stopped trying.",
  866: "You'll never find a rainbow if you're looking down.",
  867: "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
  868: "Your attitude determines your direction.",
  869: "You learn more from failure than from success.",
  870: "Your biggest challenge isn't someone else. It's the ache in your lungs and the burning in your legs.",
  871: "You may be the only person left who believes in you, but it's enough.",
  872: "Your future is created by what you do today, not tomorrow.",
  873: "You must be the change you wish to see in the world.",
  874: "Your life does not get better by chance, it gets better by change.",
  875: "You must do the things you think you cannot do.",
  876: "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
  877: "You never know how strong you are until being strong is your only choice.",
  878: "Your only limit is your mind.",
  879: "You never know what's around the corner. It could be everything. Or it could be nothing.",
  880: "Your present circumstances don't determine where you can go; they merely determine where you start.",
  881: "You only fail when you stop trying.",
  882: "Your struggles develop your strengths.",
  883: "You only live once, but if you do it right, once is enough.",
  884: "Your time is limited, so don't waste it living someone else's life.",
  885: "You were born to be real, not to be perfect.",
  886: "Your vibe attracts your tribe.",
  887: "You were born to stand out, stop trying to fit in.",
  888: "You're allowed to be both a masterpiece and a work in progress simultaneously.",
  889: "You were given this life because you are strong enough to live it.",
  890: "You're braver than you believe, stronger than you seem, and smarter than you think.",
  891: "You were not created to just survive. You were created to thrive.",
  892: "You're never too old to set another goal or to dream a new dream.",
  893: "You will face many defeats in life, but never let yourself be defeated.",
  894: "You've always had the power, my dear. You just had to learn it for yourself.",
  895: "You will find that it is necessary to let things go; simply for the reason that they are heavy.",
  896: "You are exactly where you need to be.",
  897: "You will never know your limits until you push yourself to them.",
  898: "You are never too old to become younger.",
  899: "You will never be able to escape from your heart. So it is better to listen to what it has to say.",
  900: "You are stronger than you think.",
  901: "You would not have called if you had not heard me call.",
  902: "You become what you believe.",
  903: "You'll learn, as you get older, that rules are made to be broken.",
  904: "You can have it all. Just not all at once.",
  905: "You'll never find a rainbow if you're looking down.",
  906: "You can never cross the ocean until you have the courage to lose sight of the shore.",
  907: "Your attitude determines your direction.",
  908: "You can't be great if you don't feel great.",
  909: "Your biggest challenge isn't someone else. It's the ache in your lungs and the burning in your legs.",
  910: "You can't connect the dots looking forward; you can only connect them looking backward.",
  911: "Your future is created by what you do today, not tomorrow.",
  912: "You can't fall if you don't climb. But there's no joy in living your whole life on the ground.",
  913: "Your life does not get better by chance, it gets better by change.",
  914: "You can't go back and change the beginning, but you can start where you are and change the ending.",
  915: "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
  916: "You can't stop the waves, but you can learn to surf.",
  917: "Your only limit is your mind.",
  918: "You can't use up creativity. The more you use, the more you have.",
  919: "Your present circumstances don't determine where you can go; they merely determine where you start.",
  920: "You can't wait for inspiration. You have to go after it with a club.",
  921: "Your struggles develop your strengths.",
  922: "You deserve to be happy. You deserve to live a life you are excited about.",
  923: "Your time is limited, so don't waste it living someone else's life.",
  924: "You didn't come this far to only come this far.",
  925: "Your vibe attracts your tribe.",
  926: "You don't have to be perfect to be amazing.",
  927: "You're allowed to be both a masterpiece and a work in progress simultaneously.",
  928: "You don't have to see the whole staircase, just take the first step.",
  929: "You're braver than you believe, stronger than you seem, and smarter than you think.",
  930: "You don't need anyone's permission to be yourself.",
  931: "You're never too old to set another goal or to dream a new dream.",
  932: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
  933: "You've always had the power, my dear. You just had to learn it for yourself.",
  934: "You have to accept whatever comes and the only important thing is that you meet it with courage.",
  935: "You are exactly where you need to be.",
  936: "You have to be at your strongest when you're feeling at your weakest.",
  937: "You are never too old to become younger.",
  938: "You have to fight through some bad days to earn the best days of your life.",
  939: "You are stronger than you think.",
  940: "You have to let go of who you were to become who you will be.",
  941: "You become what you believe.",
  942: "You have to love yourself before anyone else can.",
  943: "You can have it all. Just not all at once.",
  944: "You have to make the choices that are right for you.",
  945: "You can never cross the ocean until you have the courage to lose sight of the shore.",
  946: "You have to risk going too far to discover just how far you can go.",
  947: "You can't be great if you don't feel great.",
  948: "You have within you right now, everything you need to deal with whatever the world can throw at you.",
  949: "You can't connect the dots looking forward; you can only connect them looking backward.",
  950: "You haven't failed until you've stopped trying.",
  951: "You can't fall if you don't climb. But there's no joy in living your whole life on the ground.",
  952: "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
  953: "You can't go back and change the beginning, but you can start where you are and change the ending.",
  954: "You learn more from failure than from success.",
  955: "You can't stop the waves, but you can learn to surf.",
  956: "You may be the only person left who believes in you, but it's enough.",
  957: "You can't use up creativity. The more you use, the more you have.",
  958: "You must be the change you wish to see in the world.",
  959: "You can't wait for inspiration. You have to go after it with a club.",
  960: "You must do the things you think you cannot do.",
  961: "You deserve to be happy. You deserve to live a life you are excited about.",
  962: "You never know how strong you are until being strong is your only choice.",
  963: "You didn't come this far to only come this far.",
  964: "You never know what's around the corner. It could be everything. Or it could be nothing.",
  965: "You don't have to be perfect to be amazing.",
  966: "You only fail when you stop trying.",
  967: "You don't have to see the whole staircase, just take the first step.",
  968: "You only live once, but if you do it right, once is enough.",
  969: "You don't need anyone's permission to be yourself.",
  970: "You were born to be real, not to be perfect.",
  971: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
  972: "You were born to stand out, stop trying to fit in.",
  973: "You have to accept whatever comes and the only important thing is that you meet it with courage.",
  974: "You were given this life because you are strong enough to live it.",
  975: "You have to be at your strongest when you're feeling at your weakest.",
  976: "You were not created to just survive. You were created to thrive.",
  977: "You have to fight through some bad days to earn the best days of your life.",
  978: "You will face many defeats in life, but never let yourself be defeated.",
  979: "You have to let go of who you were to become who you will be.",
  980: "You will find that it is necessary to let things go; simply for the reason that they are heavy.",
  981: "You have to love yourself before anyone else can.",
  982: "You will never know your limits until you push yourself to them.",
  983: "You have to make the choices that are right for you.",
  984: "You will never be able to escape from your heart. So it is better to listen to what it has to say.",
  985: "You have to risk going too far to discover just how far you can go.",
  986: "You would not have called if you had not heard me call.",
  987: "You have within you right now, everything you need to deal with whatever the world can throw at you.",
  988: "You'll learn, as you get older, that rules are made to be broken.",
  989: "You haven't failed until you've stopped trying.",
  990: "You'll never find a rainbow if you're looking down.",
  991: "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
  992: "Your attitude determines your direction.",
  993: "You learn more from failure than from success.",
  994: "Your biggest challenge isn't someone else. It's the ache in your lungs and the burning in your legs.",
  995: "You may be the only person left who believes in you, but it's enough.",
  996: "Your future is created by what you do today, not tomorrow.",
  997: "You must be the change you wish to see in the world.",
  998: "Your life does not get better by chance, it gets better by change.",
  999: "You must do the things you think you cannot do.",
  1000: "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
  1001: "The only way to achieve the impossible is to believe it is possible.",
  1002: "Your greatest glory is not in never falling, but in rising every time you fall.",
};

export const getRandomQuote = () => {
  const quoteKeys = Object.keys(quotes);
  const randomIndex = Math.floor(Math.random() * quoteKeys.length);
  const randomKey = quoteKeys[randomIndex];
  return quotes[randomKey];
};

export const getQuoteByNumber = (num) => {
  if (!quotes[num]) {
    throw new Error(`Quote with number ${num} does not exist`);
  }
  return quotes[num];
};
